# Generated by Django 4.0.5 on 2022-07-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_myclass_in_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myclass_in_model',
            name='company_open_value',
            field=models.FloatField(null=True),
        ),
    ]
