# Generated by Django 4.0.5 on 2022-08-14 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_transacs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BP',
        ),
    ]
